### ISSUE TITLE
deep EMhancer fails in production

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#393] opened 2021-04-16 14:09 UTC
when there using halves taken from the volume:
01094:   STARTED: createOutputStep, step 3, time 2021-04-15 14:06:50.927883
01095:   Traceback (most recent call last):
01096:     File "/home/virus/SOFTWARE/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 189, in run
01097:       self._run()
01098:     File "/home/virus/SOFTWARE/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 240, in _run
01099:       resultFiles = self._runFunc()
01100:     File "/home/virus/SOFTWARE/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 236, in _runFunc
01101:       return self._func(*self._args)
01102:     File "/home/virus/SOFTWARE/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_postProcessing_deepPostProcessing.py", line 265, in createOutputStep
01103:       self._defineTransformRelation(self.inputHalf1, volume)
01104:     File "/home/virus/SOFTWARE/miniconda3/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol.py", line 154, in _defineTransformRelation
01105:       self._defineRelation(pwobj.RELATION_TRANSFORM, srcObj, dstObj)
01106:     File "/home/virus/SOFTWARE/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1281, in _defineRelation
01107:       self.mapper.insertRelation(relName, self, parentObj, childObj,
01108:     File "/home/virus/SOFTWARE/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/mapper/sqlite.py", line 433, in insertRelation
01109:       if not o.hasObjId():
01110:   AttributeError: 'NoneType' object has no attribute 'hasObjId'
01111:   Protocol failed: 'NoneType' object has no attribute 'hasObjId'
01112:   FAILED: createOutputStep, step 3, time 2021-04-15 14:06:50.945563
01113:   *** Last status is failed
01114:   ------------------- PROTOCOL FAILED (DONE 3/3)

**Comment by dmaluenda** [comment] 2021-04-16 14:18
Don't you mean 'deepEMhancer'?

**Comment by pconesa** [comment] 2021-04-17 05:33
Yep, my bad

**Comment by DaniDelHoyo** [comment] 2021-05-17 13:52
I cannot reproduce this error, in the test it passes. Could you elaborate how does the error appear? or maybe it is already solved in devel? The line of code which yields the error does not produce it in devel as it is inside an if that checks whether the halve exists

**Comment by Vilax** [comment] 2022-06-03 10:00
I checked the test, and some data. I fixed a minor issue in the test, and it seems to work. Unfortunately I was not able to find this old error. For this reason I close the issue

**Closed by Vilax** 2022-06-03 10:00 UTC
Labels: bug
