### ISSUE TITLE
arpack not found to install nma

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion-em-xmipp#88] opened 2019-04-05 13:23 UTC
I had this issue when I tried to install xmipp last time.

**Comment by dmaluenda** [comment] 2019-04-08 14:18
I've double checked this and I can't reproduce the issue nor find the bug. 'arpack' should be defined by Scipion.

Xmipp plugin might be out of date. To check if the problem is that, please, ensure that `deps=['arpack']` (instead of  `deps=[arpack]`, note the quotation) is in [this part of the code](https://github.com/I2PC/scipion-em-xmipp/blob/a3444daa5539be250e192563bd7e6bec1ce74c98/xmipp3/__init__.py#L164).

If it reads as it should (quotated), please check that Scipion have defined 'arpack' by `./scipion install --show arpack`, if not found, maybe Scipion is out of date.

Thanks!

**Comment by dmaluenda** [comment] 2019-04-25 12:41
@josuegbl, can I close this? Are still you getting this problem??

**Comment by josuegbl** [comment] 2019-04-25 14:49
Well, this is still happening when I try to install manually, as a developer:
scipion-scripts/plugins.py" "xmipp3" "--install" "nma"
Plugin: xmipp3
Inside installBinary...
Traceback (most recent call last):
  File "/home/josuegbl/SOFTWARE/SCIPION/scipion-scripts/plugins.py", line 239, in <module>
    installBinary(plugin, target=args.install[0])
  File "/home/josuegbl/SOFTWARE/SCIPION/scipion-scripts/plugins.py", line 201, in installBinary
    plugin.Plugin.defineBinaries(env)
  File "/home/josuegbl/SOFTWARE/SCIPION/plugins/scipion-em-xmipp/xmipp3/__init__.py", line 169, in defineBinaries
    % env.getLibFolder(), 'nma_diag_arpack')])
  File "/home/josuegbl/SOFTWARE/SCIPION/scipion-plug/pyworkflow/install/funcs.py", line 655, in addPackage
    target = self._addDownloadUntar(extName, **libArgs)
  File "/home/josuegbl/SOFTWARE/SCIPION/scipion-plug/pyworkflow/install/funcs.py", line 386, in _addDownloadUntar
    self._addTargetDeps(t, deps)
  File "/home/josuegbl/SOFTWARE/SCIPION/scipion-plug/pyworkflow/install/funcs.py", line 359, in _addTargetDeps
    raise Exception("Dependency '%s' does not exists. " % targetName)
Exception: Dependency 'arpack' does not exists. 

 But I tried to install nma using production version and it worked to me. 
So, I solve (at least in part) my problem, but there is still a problem in your code. 
You can close it if you want.

**Comment by dmaluenda** [comment] 2019-04-26 10:09
Sorry, but I can't find the way that you are trying to use for install binaries...

I see, you are using a 'plugins.py' script inside of 'scipion-scripts' folder (is this [the scipion-scripts repo](https://github.com/I2PC/scipion-scripts)?) that I'm not capable to find anywhere... and I'm never seen the `"...scipion-scripts/plugins.py" "xmipp3" "--install" "nma"` command to install a binary.

Nowadays, the supported way to install binaries is either from the 'Plugin Manager' or by `scipion installb binaryName` (where binaryName is 'nma' in this case). I've just checked both ways and they work fine.

The error that you are getting seems that is due to the 'env' (in 'plugin.Plugin.defineBinaries(env)' at line 201 of 'scipion-scripts/plugins.py') is not properly populated, but I can't explore it since I can't find that script.

I have no inconvenience to keep exploring this when you point me out where to find the 'scipion-scripts/plugins.py' script.

Thx!

**Comment by delarosatrevin** [comment] 2019-04-26 10:52
@josuegbl , @dmaluenda is right, you are trying to install the binaries in non-standard (non-supported) way. Remember that this scripts is just for my own developing/testing purposes. Nonetheless, there is an updated version here:

https://github.com/delarosatrevin/scipion-em-plugins/blob/master/plugins.py

Regarding the binaries, there are a couple things I would like to simplify there.

**Comment by dmaluenda** [comment] 2019-04-26 11:40
Thank's for clarifying @delarosatrevin ! I was totally lost XD.

I will have a look on it.

**Comment by dmaluenda** [comment] 2019-05-16 07:53
I think that the problem is [the createEnviroment() function](https://github.com/delarosatrevin/scipion-em-plugins/blob/975f1dc2859e9d004c5ba4ec9e6824265c28f1c3/plugins.py#L73). Maybe it can be fixed if `env = Enviroment()` is substituted by `env = pyworkflow.install.script.defineBinaries()`. In this way `env` will be populated with all Scipion's defined targets.

I will close this. Feel free to re-open it ;-p

**Closed by dmaluenda** 2019-05-16 07:53 UTC
